feat: add cors validation
Nadrieril/dhall-rust pull request #214
Opened 2021-03-23 23:00 UTC by kryptn

I needed CORS validation for a [project](https://github.com/kryptn/http-client) I'm working on 

My first dive into rust, so I'm not sure what else would be necessary to call this good to go, so I'm looking for feedback.

Thanks!

2021-04-03 12:10 UTC, Nadrieril commented
Hi! Thanks for taking the time to do this, I never took the time. I'll trust you on the details, this looks pretty good!
Did you manage to test this? I'd really like for there to be a test to ensure this keeps working in the future. I thought I remembered that the main dhall-lang repo had such a test but I can't find it.

2021-04-03 12:26 UTC, Nadrieril commented
@Gabriel439 do you test CORS compliance on the Haskell codebase? I thought I remembered you setting up something on dhall-lang.org to help this testing, but I can't find it anymore.

2021-04-03 19:36 UTC, Gabriel439 commented
@Nadrieril: I don't have automated testing around this, yet.  You might be thinking of test.dhall-lang.org, which was created to test custom headers

2021-04-08 13:27 UTC, Nadrieril commented
Oh right, that's what I got it mixed with. I see there's a relevant issue already (https://github.com/dhall-lang/dhall-lang/issues/1130), let's talk there

2021-04-08 16:33 UTC, kryptn commented
> Did you manage to test this? I'd really like for there to be a test to ensure this keeps working in the future.

No not yet, but absolutely agreed. I figured I'd seek feedback on the implementation itself first and then see what can be done with testing.

2021-04-12 16:25 UTC, Nadrieril commented on dhall/src/semantics/resolve/resolve.rs
> +) -> Result<(), Error> {
I'd prefer that `cors_check` take origin as a String, and that testing whether `origin` is `None` be done outside of it.

2021-04-12 16:27 UTC, Nadrieril commented
I looked it over again and apart from the comment above I'm ok with the implementation :) Happy to merge it as soon as we figure out testing.

2021-05-01 19:53 UTC, Nadrieril requested changes

2021-05-01 19:53 UTC, Nadrieril commented on dhall/src/semantics/resolve/resolve.rs
> +        .head(&remote.to_string())
This should be a OPTIONS request, not a HEAD request

2021-05-01 19:53 UTC, Nadrieril commented on dhall/src/semantics/resolve/resolve.rs
> +        && headers[reqwest::header::ACCESS_CONTROL_ALLOW_ORIGIN] != origin
This can panic if the `ACCESS_CONTROL_ALLOW_ORIGIN` header is not present. You should handle that case

2021-05-01 19:53 UTC, Nadrieril commented on dhall/src/semantics/resolve/resolve.rs
> +        && headers[reqwest::header::ACCESS_CONTROL_ALLOW_ORIGIN] != origin
`origin` looks like `https://example.com`, but the header won't have the `https://` part, so this will never succeed

2021-05-01 19:53 UTC, Nadrieril commented on dhall/src/semantics/resolve/resolve.rs
> +        .header(reqwest::header::USER_AGENT, "dhall-rust");
The `ORIGIN` header should be set here too to match the CORS request

2021-05-01 19:53 UTC, Nadrieril commented on dhall/src/semantics/resolve/resolve.rs
> +        format!("{}://{}", remote.scheme(), remote.host_str().unwrap());
I think you should use https://docs.rs/reqwest/0.11.3/reqwest/struct.Url.html#method.origin here to be properly standard-compliant

2021-05-01 19:54 UTC, Nadrieril commented
I tried to run some test and it appears the implementation has a few errors. I added some comments

2021-05-08 03:57 UTC, kryptn commented
Thanks! I'll get to resolving these.

2021-05-10 21:03 UTC, Nadrieril commented
FYI latest commit on dhall-lang now has a decent set of CORS tests!

2021-05-10 21:09 UTC, kryptn commented
Oh awesome! This will make validating the implementation much easier, thank you!

2021-09-10 21:57 UTC, Nadrieril commented
Hey, how are you getting on with this? Are you still working on this? Would you like some help?

2021-09-15 19:53 UTC, kryptn commented
I'll see where I can get with this over this upcoming weekend. iirc I might need some help with one of your suggestions, but I'll have to regain this context and likely update code.

2022-02-02 21:05 UTC, kryptn commented
I don't think I'm going to finish this, the project I was working on that needed this didn't really work the way I wanted it to. 

I won't get rid of my fork/branch though, just in case someone wants to take it over.

2022-02-02 21:05 UTC, closed without merging

2022-02-07 23:16 UTC, Nadrieril commented
No problem, thanks for letting me know! :)